name: LibCPUID tests

on: [push, pull_request]

jobs:
  libcpuid-tests:
    name: Linux x64_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clone LibCPUID repository
      run: git clone https://github.com/anrieff/libcpuid.git /tmp/libcpuid

    - name: Run test script
      run: bash ./scripts/run_libcpuid_tests.sh "/tmp/libcpuid/tests"
